// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_atualizar_id_ from "./routes/api/atualizar/[id].ts";
import * as $api_deletar_id_ from "./routes/api/deletar/[id].ts";
import * as $api_formulario from "./routes/api/formulario.ts";
import * as $api_lista from "./routes/api/lista.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_register from "./routes/api/register.ts";
import * as $api_sair from "./routes/api/sair.ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $formulario from "./islands/formulario.tsx";
import * as $lista from "./islands/lista.tsx";
import * as $login from "./islands/login.tsx";
import * as $register from "./islands/register.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/atualizar/[id].ts": $api_atualizar_id_,
    "./routes/api/deletar/[id].ts": $api_deletar_id_,
    "./routes/api/formulario.ts": $api_formulario,
    "./routes/api/lista.ts": $api_lista,
    "./routes/api/login.ts": $api_login,
    "./routes/api/register.ts": $api_register,
    "./routes/api/sair.ts": $api_sair,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/formulario.tsx": $formulario,
    "./islands/lista.tsx": $lista,
    "./islands/login.tsx": $login,
    "./islands/register.tsx": $register,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
